# Generated by Django 3.2.6 on 2021-09-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educationinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(max_length=50)),
                ('current_occupation', models.CharField(max_length=50)),
                ('working_experience_year', models.CharField(max_length=20)),
            ],
        ),
    ]
