# Generated by Django 3.2.6 on 2021-09-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_educationinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationinfo',
            old_name='current_occupation',
            new_name='field_of_study',
        ),
        migrations.AddField(
            model_name='educationinfo',
            name='skills',
            field=models.JSONField(default=dict),
        ),
    ]
