# Generated by Django 3.2.6 on 2021-09-04 14:52

from django.db import migrations, models
import django.db.models.deletion
import job.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=50)),
                ('job_description', models.CharField(max_length=500)),
                ('job_thumnail', models.ImageField(upload_to=job.models.upload_location)),
                ('job_average_salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Material_skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='materials_table',
            fields=[
                ('material_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('material_name', models.CharField(max_length=50)),
                ('skill_gained', models.CharField(max_length=50)),
                ('material_type', models.CharField(max_length=50)),
                ('material_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=50)),
                ('skills_desc', models.CharField(max_length=50)),
                ('skill_type', models.CharField(max_length=50)),
                ('skill_material_id', models.ManyToManyField(through='job.Material_skill', to='job.materials_table')),
            ],
        ),
        migrations.AddField(
            model_name='material_skill',
            name='inter_material_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.materials_table'),
        ),
        migrations.AddField(
            model_name='material_skill',
            name='inter_skills_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.skill'),
        ),
        migrations.CreateModel(
            name='Job_skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inter_job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('inter_skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.skill')),
            ],
            options={
                'unique_together': {('inter_job_id', 'inter_skill_id')},
            },
        ),
        migrations.AddField(
            model_name='job',
            name='job_skill_id',
            field=models.ManyToManyField(through='job.Job_skill', to='job.Skill'),
        ),
        migrations.AlterUniqueTogether(
            name='material_skill',
            unique_together={('inter_material_id', 'inter_skills_id')},
        ),
    ]
