# Generated by Django 3.2.6 on 2021-09-05 11:04

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_thumnail',
            field=models.ImageField(default='displayjob/default/download.jpeg', upload_to=job.models.upload_location),
        ),
    ]
