# Generated by Django 3.2.6 on 2021-09-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_job_job_thumnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(default=dict, max_length=250),
            preserve_default=False,
        ),
    ]
