# Generated by Django 3.2.6 on 2021-09-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_education',
            field=models.JSONField(default=dict),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(),
        ),
    ]
